theme: jekyll-theme-cayman
title: CodeWeek Austria
description: Die EU Code Week ist eine Breiteninitiative zur Feier von Kreativität, Problemlösung und Zusammenarbeit durch Programmierung und andere technische Aktivitäten.
